Repository NETWAYS/ansible-collection-elasticstack, pull requests merged in 2023-09, with the labels that each got.

#249 Make logstash_writer user password hashing idempotent
  .github/workflows/test_full_stack.yml
  .github/workflows/test_roles_pr.yml
  README.md
  docs/role-logstash.md
  molecule/beats_default/converge.yml
  molecule/beats_peculiar/converge.yml
  molecule/elasticsearch_cluster-oss/converge.yml
  molecule/elasticsearch_no-security/converge.yml
  molecule/elasticsearch_roles_calculation/converge.yml
  molecule/elasticstack_default/converge.yml
  molecule/kibana_default/converge.yml
  molecule/logstash_full_stack-oss/converge.yml
  molecule/logstash_pipelines/converge.yml
  molecule/logstash_specific_version/converge.yml
  molecule/repos_default/converge.yml
  molecule/repos_oss/converge.yml
  requirements-test.txt
  roles/beats/defaults/main.yml
  roles/beats/tasks/beats-security.yml
  roles/elasticsearch/defaults/main.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/elasticsearch/tasks/main.yml
  roles/kibana/defaults/main.yml
  roles/kibana/tasks/kibana-security.yml
  roles/kibana/tasks/main.yml
  roles/logstash/defaults/main.yml
  roles/logstash/tasks/logstash-security.yml
  roles/logstash/templates/logstash.yml.j2
  roles/logstash/templates/logstash_writer_user.j2
  roles/repos/defaults/main.yml
Labels: bug

#255 Configure Galaxy in Molecule
  molecule/elasticsearch_cluster-oss/molecule.yml
  molecule/elasticsearch_default/molecule.yml
  molecule/elasticsearch_no-security/molecule.yml
  molecule/elasticsearch_roles_calculation/molecule.yml
  molecule/elasticstack_default/molecule.yml
  molecule/logstash_full_stack-oss/molecule.yml
  molecule/logstash_pipelines/molecule.yml
  molecule/logstash_specific_version/molecule.yml
  molecule/repos_default/molecule.yml
  molecule/repos_oss/molecule.yml
Labels: bug, dependencies

#213 Install cryptography Python library
  docs/role-beats.md
  docs/role-elasticsearch.md
  docs/role-kibana.md
  docs/role-logstash.md
  roles/beats/defaults/main.yml
  roles/beats/tasks/beats-security.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/kibana/tasks/kibana-security.yml
  roles/logstash/tasks/logstash-security.yml
Labels: enhancement

#268 Remove redundant Beats include in test
  molecule/elasticstack_default/converge.yml
Labels: bug

#186 Feature/use uri not curl 123
  README.md
  docs/role-logstash.md
  requirements-test.txt
  roles/elasticsearch/tasks/elasticsearch-keystore.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/elasticsearch/tasks/main.yml
  roles/elasticsearch/templates/elasticsearch.yml.j2
  roles/logstash/defaults/main.yml
  roles/logstash/tasks/logstash-security.yml
  roles/logstash/templates/logstash_writer_user.j2
Labels: help wanted

#270 Add "extra config" to `kibana.yml`
  docs/role-kibana.md
  molecule/elasticstack_default/converge.yml
  roles/kibana/templates/kibana.yml.j2
Labels: enhancement
