Repository NETWAYS/ansible-collection-elasticstack, pull requests merged in 2023-02, with the labels that each got.

#29 Fix issues with pam_limits
  README.md
  docs/role-elasticsearch.md
  galaxy.yml
  molecule/elasticsearch_cluster-8/requirements.yml
  molecule/elasticsearch_cluster-oss/requirements.yml
  molecule/elasticsearch_cluster/requirements.yml
  molecule/elasticsearch_default/requirements.yml
  molecule/elasticsearch_no-security/requirements.yml
  molecule/kibana_full_stack-oss/prepare.yml
  molecule/kibana_full_stack/prepare.yml
  requirements-test.txt
  roles/elasticsearch/defaults/main.yml
  roles/elasticsearch/tasks/main.yml
  roles/elasticsearch/tests/inventory
  roles/elasticsearch/tests/test.yml
  roles/logstash/tasks/logstash-security.yml
Labels: bug, documentation, enhancement

#9 Disable discovery on single node clusters
  roles/elasticsearch/templates/elasticsearch.yml.j2
Labels: enhancement

#34 Add note about hardcoded host groups
  README.md
Labels: documentation

#30 Make sure all certificates contain used hostnames
  roles/beats/tasks/beats-security.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/kibana/tasks/kibana-security.yml
  roles/logstash/tasks/logstash-security.yml
Labels: bug, enhancement

#43 Add rpm based checks for full stack
  .github/workflows/test_full_stack.yml
Labels: enhancement

#44 Use verify from cluster 8
  molecule/elasticsearch_cluster/verify.yml
Labels: enhancement

#47 Fix combination of oss and release version
  molecule/elasticstack_default/converge.yml
  molecule/repos_oss/converge.yml
Labels: bug

#53 Fix no-security cluster
  molecule/elasticsearch_no-security/verify.yml
Labels: bug

#52 Fix verify for new Kibana API
  molecule/kibana_full_stack/verify.yml
Labels: bug

#48 Fix/lint 100
  .config/ansible-lint.yml
  .github/workflows/test_full_stack.yml
  .github/workflows/test_role_beats.yml
  .github/workflows/test_role_elasticsearch.yml
  .github/workflows/test_role_kibana.yml
  .github/workflows/test_role_logstash.yml
  .github/workflows/test_role_repos.yml
  .github/workflows/test_roles_pr.yml
  molecule/kibana_full_stack/verify.yml
  molecule/logstash_run_logstash/converge.yml
  molecule/logstash_specific_version/converge.yml
  molecule/repos_default/requirements.yml
  molecule/repos_oss/requirements.yml
  roles/elasticsearch/defaults/main.yml
  roles/elasticsearch/meta/main.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/elasticsearch/tasks/main.yml
  roles/kibana/meta/main.yml
  roles/kibana/tasks/kibana-security.yml
  roles/kibana/tasks/main.yml
  roles/logstash/tasks/main.yml
  roles/repos/meta/main.yml
  roles/repos/tasks/main.yml
  roles/repos/tasks/redhat.yml
  roles/repos/tasks/suse.yml
Labels: enhancement

#82 Fix capitalization of namespace
  docs/getting-started.md
  docs/role-beats.md
  docs/role-elasticsearch.md
  docs/role-kibana.md
  docs/role-logstash.md
  docs/role-repos.md
  galaxy.yml
  molecule/beats_default/converge.yml
  molecule/beats_full_stack/converge.yml
  molecule/beats_peculiar/converge.yml
  molecule/beats_peculiar/verify.yml
  molecule/elasticsearch_cluster-oss/converge.yml
  molecule/elasticsearch_cluster/converge.yml
  molecule/elasticsearch_default/converge.yml
  molecule/elasticsearch_no-security/converge.yml
  molecule/elasticstack_default/converge.yml
  molecule/kibana_default/converge.yml
  molecule/kibana_full_stack-oss/converge.yml
  molecule/kibana_full_stack/converge.yml
  molecule/logstash_default/converge.yml
  molecule/logstash_full_stack-oss/converge.yml
  molecule/logstash_full_stack/converge.yml
  molecule/logstash_pipelines/converge.yml
  molecule/logstash_run_logstash/converge.yml
  molecule/logstash_specific_version/converge.yml
  molecule/repos_default/converge.yml
  molecule/repos_oss/converge.yml
  roles/logstash/templates/log4j2.properties.j2
  roles/logstash/templates/pipelines.yml.j2
Labels: bug, documentation

#88 Lint full codebase before merging
  .github/workflows/test_full_stack.yml
  .github/workflows/test_roles_pr.yml
  molecule/repos_oss/prepare.yml
Labels: enhancement

#94 Reduced heap size in elasticsearch scenarios
  molecule/elasticsearch_cluster-oss/converge.yml
  molecule/elasticsearch_cluster/converge.yml
  molecule/elasticsearch_default/converge.yml
  molecule/elasticsearch_no-security/converge.yml
  molecule/elasticstack_default/converge.yml
Labels: documentation, enhancement

#97 Only test OS where tests work
  .github/workflows/test_full_stack.yml
  README.md
  roles/beats/meta/main.yml
  roles/elasticsearch/meta/main.yml
  roles/kibana/meta/main.yml
  roles/logstash/meta/main.yml
  roles/repos/meta/main.yml
Labels: documentation

#107 Fixed pam_limits module deprecation warning
  roles/elasticsearch/tasks/main.yml
Labels: enhancement

#113 Failsafe for standalone usage
  molecule/logstash_pipelines/converge.yml
  roles/beats/tasks/main.yml
  roles/elasticsearch/handlers/main.yml
  roles/elasticsearch/tasks/elasticsearch-security.yml
  roles/kibana/tasks/kibana-security.yml
  roles/logstash/tasks/logstash-security.yml
  roles/logstash/templates/elasticsearch-output.conf.j2
  roles/logstash/templates/logstash.yml.j2
Labels: bug
