Repository NETWAYS/ansible-collection-elasticstack, pull requests merged in 2024-02, with the labels that each got.

#310 fixed filebeat config template to actually use tcp and udp port vars
  roles/beats/templates/filebeat.yml.j2
Labels: bug

#314 Enforce repos only with full stack
  roles/beats/tasks/auditbeat.yml
  roles/beats/tasks/filebeat.yml
  roles/beats/tasks/metricbeat.yml
  roles/elasticsearch/tasks/main.yml
  roles/kibana/tasks/main.yml
  roles/logstash/tasks/main.yml
Labels: bug

#307 Fix apt key handling2
  roles/repos/defaults/main.yml
  roles/repos/tasks/debian.yml
  roles/repos/tasks/redhat.yml
Labels: bug

#308 Add elasticsearch_role and elasticsearch_user module
  .github/workflows/test_elasticsearch_modules.yml
  .gitignore
  README.md
  docs/module-elasticsearch_role.md
  docs/module-elasticsearch_user.md
  molecule/elasticsearch_test_modules/converge.yml
  molecule/elasticsearch_test_modules/molecule.yml
  molecule/elasticsearch_test_modules/prepare.yml
  molecule/elasticsearch_test_modules/requirements.yml
  plugins/module_utils/api.py
  plugins/module_utils/elasticsearch_role.py
  plugins/module_utils/elasticsearch_user.py
  plugins/modules/elasticsearch_role.py
  plugins/modules/elasticsearch_user.py
  requirements-test.txt
Labels: feature

#318 Add new authors to `AUTHORS`
  .mailmap
  AUTHORS
Labels: documentation
